/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 link.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function LinkBase(props) {
  const { nodes, materials } = useGLTF('/link.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SOLID.geometry} material={materials.STEP_ff00ff} scale={0.001} />
    </group>
  )
}

export function LinkNext(props) {
  const { nodes, materials } = useGLTF('/link_s.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SOLID.geometry} material={materials.STEP_ff00ff} scale={0.001} />
    </group>
  )
}

export function Base(props)  {
    const { nodes, materials } = useGLTF('/base.glb')
    if (!props.isBase) {
        return null;
    }
    return (
      <group {...props} dispose={null}>
        <group scale={0.001}>
          <mesh geometry={nodes.SOLID.geometry} material={materials.Steel} rotation={[0, 0, Math.PI]} />
        </group>
      </group>
    )
  }

useGLTF.preload('/link.glb')
